#spring:
#  datasource:
#    #url: jdbc:mysql://localhost:3306/sample  ## 1. 기존 사용하던 jdbc:mysql 로 시작하는 url 주석처리 후 jdbc:log4jdbc:mysql 로 시작하는 url 로 변경.
#    url: jdbc:log4jdbc:mysql://localhost:3306/nara?serverTimezone=UTC
#    username: narauser
#    password: nara0903
#    #driver-class-name: com.mysql.jdbc.Driver ## 2. 기존 사용하던 com.mysql.jdbc.Driver를 net.sf.log4jdbc.sql.jdbcapi.DriverSpy 로 변경.
#    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
#    hikari:
#      connection-timeout: 5000
#      validation-timeout: 1000
#      maximum-pool-size: 30
#      minimum-idle: 2
#      connection-test-query: SELECT 1

#logging:
#  level:
#    jdbc.sqltiming: DEBUG
#    org.springframework.web: DEBUG
#    com.zaxxer.hikari.HikariDataSource: ERROR