# server port
server:  port: 9090

# mvc
spring:  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp
  datasource:    url: jdbc:log4jdbc:mysql://localhost:3306/nara?serverTimezone=UTC
    username: narauser
    password: nara0903
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:      connection-test-query: select 1
      connection-timeout: 5000
      maximum-pool-size: 30
      validation-timeout: 1000
      minimum-idle: 2 
      
